# Workflow pour compiler et déployer une application Vite sur GitHub Pages
name: Deploy Vite site to Pages

on:
  # Déclenche l'action à chaque push sur la branche principale
  push:
    branches: ["main"]

  # Permet de lancer ce workflow manuellement depuis l'onglet Actions
  workflow_dispatch:

# Définit les permissions du GITHUB_TOKEN pour permettre le déploiement
permissions:
  contents: read
  pages: write
  id-token: write

# Permet une seule exécution simultanée
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Job de compilation
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: npm run build
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  # Job de déploiement
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
